#!/bin/sh

NON_SRC_EXTENSIONS='
    *.beam
    *.dump
    *.pyc
    *.out
    *.cmi
    *.cmo
    *.cmx
    *.o
    *.hi
'


NON_SRC_EXTENSIONS_FIND_SYNTAX=`
    echo $NON_SRC_EXTENSIONS | sed 's/\ /\ -or\ -name\ /g'
`


find . -name $NON_SRC_EXTENSIONS_FIND_SYNTAX | xargs rm -f
