.PHONY: compile clean

compile:
	@ocamlbuild -use-ocamlfind -pkg num solution_015_binomial_via_factorial.byte
	@ocamlbuild -use-ocamlfind -pkg num solution_015_binomial_via_pascal_triangle.byte

clean:
	@ocamlbuild -clean
